import React from 'react';
import ReactDOM from 'react-dom';
import './assets/styles/reset.css';
import './assets/fonts/iconfont.css';
import App from './App';
import 'antd-mobile/dist/antd-mobile.css';
import './utils/axiosUtil';
import {Provider} from 'react-redux';
import store from './store';
ReactDOM.render(<Provider store={store}><App/></Provider>,document.getElementById('root'));